### ISSUE TITLE
Search still broken!

### ISSUE THREAD

**Issue by seansaville** [CSTIB-Hotel/OTCAnalyser#15]
See title. Getting a bunch of InvalidTaxonomyExceptions from the GUI, and some NullPointerExceptions in the communication layer. I'm trying to fix this now but would appreciate all hands on deck if you're in the lab.

@weiszg @waiwaing @alistairfisher

**Comment by waiwaing** [comment]
So I have taken out the search code and search now returns all rows. I have no idea why nothing displays, but it is returning 261 trades.

**Comment by seansaville** [comment]
Search should deal with rounded notional amount, not option strike price
Also, notional currency for currency

**Comment by waiwaing** [comment]
Am no longer able to reproduce problems with searching for dates.

**Comment by waiwaing** [comment]
Search no longer broken. Hopefully.

**Comment by seansaville** [comment]
On what branch is search fixed? On master I'm either getting 0 trades for every search result, or an SQLException whenever I specify values for min/max price.

**Comment by lmp47** [comment]
I can get some trades for some searches on the dataanalysis branch. I can get no swaps, but options yield results. When I search for Commodity-All-n/a-Cash with trade type Option from 1 January 2010 to 1 January 2015 with min price 0 and max price 1 (and everything else blank), I get Rounded Notional Amount 1s with values ranging from 0 to 970000 (and maybe even higher).

I think I'm using the latest database and master branch code with a few additions: I added code to the database to handle error code -5504 in addition to -21 so that it wouldn't crash every time I started it up without deleting the previous database files, and I (maybe incorrectly) modified PriceFormingContinuationData because I think there was a typo (47 instead of 4), and it couldn't handle the "partialexercise" string that came up.

**Comment by seansaville** [comment]
I'm getting the following output to the console if I have a value in the maxPrice field:
> Wrong data type: type: VARCHAR (12) expected: BIGINT value: 10,000,000
> Search failed
I'm really really confused by this now

**Comment by waiwaing** [comment]
My initial gut feeling is that your database has not been deleted in a while and thus is based on an old schema that's no longer compatible. Would suggest deleting db and retrying.



—

**Comment by seansaville** [comment]
@waiwaing That seems to have fixed the issues I was getting.
@lmp47 Can you push the modification to PFCD to master please when you get a chance? Would appreciate as few exceptions as possible while I'm debugging

**Comment by lmp47** [comment]
I added the modification. By the way, I know why it's impossible to get swaps: everything is an option. Option is the default trade type in Trade.java, and TradeType is never set for trades that are put into the database (which should probably be done in ParseZIP), so all trades in the database are options.

**Comment by lmp47** [comment]
@waiwaing In the Database.java's search method, shouldn't the conditions of the if statements for adding to the query be negated? As it is now, it seems like it will, for example, only check for currencies if the search object has a null or empty currency string.

**Comment by seansaville** [comment]
I'll fix the option/swap thing in a second. Getting another search-related issue, I'm gonna file a more specific bug report

**Comment by lmp47** [comment]
@waiwaing I've negated the conditions in the search method, and these changes are now on the dataanalysis and master branches. I think this should work, but if these changes are incorrect, please correct them.
